apiVersion: batch/v1
kind: CronJob
metadata:
  name: ml-train
spec:
  schedule: "*/5 * * * *" # Runs every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ml-train
              image: localhost/ml-train:latest
              imagePullPolicy: Never
              env:
                - name: MODEL_PATH
                  value: /mnt/model/model.joblib
                - name: MLFLOW_TRACKING_URI
                  value: http://mlflow-svc:5000
              volumeMounts:
                - mountPath: /mnt/model
                  name: model-pv
                - mountPath: /mlflow
                  name: mlflow-pv
          restartPolicy: OnFailure
          volumes:
            - name: mlflow-pv
              persistentVolumeClaim:
                claimName: mlflow-pvc
            - name: model-pv
              persistentVolumeClaim:
                claimName: model-pvc
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ml-train-initial
  labels:
    app: ml-train
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: ml-train
    spec:
      restartPolicy: OnFailure
      containers:
        - name: ml-train
          image: localhost/ml-train:latest
          imagePullPolicy: Never
          env:
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow-svc:5000
          volumeMounts:
            - mountPath: /mlflow
              name: mlflow-pv
            - mountPath: /mnt/model
              name: model-pv
      volumes:
        - name: mlflow-pv
          persistentVolumeClaim:
            claimName: mlflow-pvc
        - name: model-pv
          persistentVolumeClaim:
            claimName: model-pvc
