apiVersion: batch/v1
kind: CronJob
metadata:
  name: ml-train
spec:
  schedule: "0 * * * *" # Runs every hour at minute 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ml-train
              image: localhost/ml-train:latest
              imagePullPolicy: Never
              env:
                - name: MODEL_PATH
                  value: /mnt/model/model.joblib
                - name: MLFLOW_TRACKING_URI
                  value: http://mlflow-svc:5000
              volumeMounts:
                - mountPath: /mnt/model
                  name: model-pv
          restartPolicy: OnFailure
          volumes:
            - name: model-pv
              persistentVolumeClaim:
                claimName: model-pvc
